### PR TITLE
CLI list

### PR DESCRIPTION
**Pull request by alexeymorozov**
See #94

### CODE REVIEW

**Comment by alexeymorozov** [comment]
Github fails to run tests today. Though specs run successfully locally, I'll recheck before merging

**Review by ronaldtse — APPROVED** [review]
LGTM, thanks @alexeymorozov !

**Comment by ronaldtse** [comment]
@alexeymorozov could you help rebase this PR? Thanks!

**Comment by alexeymorozov** [comment]
@ronaldtse Thank you for rebasing 🙏 🙂

**Comment by ronaldtse** [comment]
:-)

**Pull request merged**
