### PR TITLE
metanorma/metanorma#170 add ruby 3.0 back to test matrix

### PR DESCRIPTION
**Pull request by CAMOBAP**
- metanorma/metanorma#170

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP ttfunk has an issue where 1.6.2 is the last version that supports 2.4. Removal of the gem spec version constraint will cause installation on 2.4 to fail.

**Comment by CAMOBAP** [comment]
@ronaldtse thanks for the comment, now we have `"ttfunk", "~> 1.6"` requirement it means that for `2.4` it will install `1.6.2.1` and for ruby 3.0 it will install `1.7`

As you may see on CI for 2.4 all tests passed

**Comment by ronaldtse** [comment]
That’s wonderful — didn’t know it would work 😉  thanks!

**Comment by alexeymorozov** [comment]
Hmmm :) Nice! Thanks)

**Pull request merged**
