### PR TITLE
WIP: Add formulas for Segoe UI fonts

### PR DESCRIPTION
**Pull request by abunashir**
Work In Progress!

### CODE REVIEW

**Comment by abunashir** [comment]
@ronaldtse: Turns out there are some checksum validation errors while extracting this fonts. Here is a screenshot form my linux devise using cabextract

Screen Shot 2020-06-13 at 12 17 51 PM


Is there any other source we can download this font from?

**Comment by ronaldtse** [comment]
@abunashir that's strange. I tried the English and German versions, but I'm able to extract using Keka on macOS with both files. Maybe it is some decompression issue?

Screen Shot 2020-06-13 at 11 27 08 PM
Screen Shot 2020-06-13 at 11 29 13 PM

I tried `cabextract` and ran into this too:
```sh
Extracting cabinet: xlview.msi.cab
  extracting XLVPRTID.XML
xlview.msi.cab: WARNING; bad block checksum found
XLVPRTID.XML: decompression error
...
```

And there is no documentation of this issue anywhere. This may be a dead end... :-|

**Comment by ronaldtse** [comment]
The fact is cabextract is mistaking the contents of `xlview.msi` with the sub-cabinet `XLVIEW.CAB`.

OMG it worked -- `7z e xlview.msi` works.

i.e. this worked:
```
cabextract ExcelViewer.exe 
7z e xlview.msi
cabextract XLVIEW.CAB
```

7z for Ruby https://github.com/masamitsu-murase/seven_zip_ruby

**Comment by ronaldtse** [comment]
@abunashir I found a way to extract this.

Use the gem `ruby-ole`.

```
irb(main):003:0> require 'ole/storage'
=> true
irb(main):004:0> ole = Ole::Storage.open('xlview.msi') 
=> #<Ole::Storage io=#<File:xlview.msi> root=#<Dirent:"Root Entry">>
irb(main):005:0> puts ole.dir.entries('.')
.
..
䡀䆒䑲
䡀䌏䈯
䡀䒏䗱
䡀㲞䈝䗻
䡀䈖䌧䠤
䡀䌋䄱䜵
䡀䌍䏤䊲
䡀䏌䖤䠶
䡀䕎䒵䠵
䡀䕙䊲䇒
㵡㲟䀎㬾㫊
䌋䄱䜵㷾䚨
䌋䄱䜵㾾䠳
䡀㬿䏲䐸䖱
䡀㽿䅤䈯䠶
䡀䈏䗤䕸䠨
䡀䈛䌪䗶䜵
䡀䋌䆨㫮䛲
䡀䋜䕲䆷䗸
䡀䒌䗱䒵䠯
䡀䕙䓲䕨䜷
䌋䄱䜵䏾䑬䠨
䡀䆊䌷䑲䈝䗻
䡀䈛㵪䆲䗤䕲
䡀䈝䗻䗜䏼䠨
䡀䌍䈵䗦䕲䠼
䡀䒌䓰䑲䑨䠷
䡀䓊㼳䄨䆵䠫
䌋䄱䜵㮾䆻䄯䠰
䡀㼿䕷䑬㭪䗤䠤
䡀㼿䕷䑬㹪䒲䠯
䡀㿿䏤䇬䗤䒬䠱
䡀䄛䌧㫲䗸䒷䠱
䡀䒌䓰䒕䄦䒷䠵
䡀䒌䗱䒵㮯䈹䗱
䡀䕌䄨䈷䒏䇯䕨
䡀䖖㪬䖶䐨䏥䠼
䡀䖖㯬䏬㱨䖤䠫
䡀䖖㼬㬏䜋䄳䖶
䡀䘌䗶䐲䆊䌷䑲
䡀䙎䑨㶷䓤䌳䊱
䌋䄱䜵㻾䓨䌤㫵䓰
䌋䄱䜵䀾䌫䈷䄋䠵
䆒䑲䛾䙯䌺䒦䞱䛨䠨
䌋䄱䜵㮾䆻䄯䀰䌫䈷
䌋䄱䜵㹾䝸䏽㲨䒦䠱
䌋䄱䜵㽾䓲䆒䑲㶋䠙
䡀䄕䑸䋦䒌䇱䗬䒬䠱
䡀䇊䌰㾱㼒䔨䈸䆱䠨
䡀䒌䗱䒵㬯䑲䌧䌷䑲
䡀䖖㪬䖶䐨䏥㷼䐤䠨
䡀䘙䏥䖬㬫䐲䒳䈱䗱
䌋䄱䜵㾾䌱䖱䄷䏯䐋䠳
䡀䈏䗤䕸㬨䐲䒳䈱䗱䠶
䡀䑒䗶䏤㾯㼒䔨䈸䆱䠨
䌋䄱䜵㪾䒥䗵䖖㬬䞊䏧䠯
䌋䄱䜵㼾䖻䑞䑬䗶䏤㬯䠊
䡀䇊䌰㮱䈻䘦䈷䈜䘴䑨䈦
䡀䇊䗹䛎䆨䗸㼨䔨䈸䆱䠨
䡀䛜㶶䐶䈐㬱䐲䒳䈱䗱䠶
䡀䑒䗶䏤㮯䈻䘦䈷䈜䘴䑨䈦
DigitalSignature
SummaryInformation
=> nil
```

Woot. All the names are messed up. We don't know which file is the correct one. This may be a bug of the gem (displaying files in garbled characters). However, I know that the file size of "XLVIEW.CAB" is `38865140`.

```
irb(main):068:0> puts ole.file.size('䡀䆒䑲')
4
=> nil
irb(main):069:0> puts ole.file.size('䡀䌏䈯')
1420
=> nil
irb(main):070:0> puts ole.file.size('䡀䒏䗱')
112
=> nil
irb(main):071:0> puts ole.file.size('䡀㲞䈝䗻')
36
=> nil
irb(main):072:0> puts ole.file.size('䡀䈖䌧䠤')
14
=> nil
irb(main):073:0> puts ole.file.size('䡀䌋䄱䜵')
48
=> nil
irb(main):074:0> puts ole.file.size('䡀䌍䏤䊲')
374
=> nil
irb(main):075:0> puts ole.file.size('䡀䏌䖤䠶')
52
=> nil
irb(main):076:0> puts ole.file.size('䡀䕎䒵䠵')
504
=> nil
irb(main):077:0> puts ole.file.size('䡀䕙䊲䇒')
24
=> nil
irb(main):078:0> puts ole.file.size('㵡㲟䀎㬾㫊')
38865140
=> nil
```

Now we know the file is '㵡㲟䀎㬾㫊'.

Then we can proceed to write out the file in a new location:

```
File.open('XLVIEW.CAB','w') do |file|;  file.write(ole.file.read('㵡㲟䀎㬾㫊')); end
```

Then:
```
$ cabextract XLVIEW.CAB 
Extracting cabinet: XLVIEW.CAB
  extracting XLVPRTID.XML
  extracting XLVIEW.EXE
  extracting XLVIEW.MAN
  extracting XLVINTL32.DLL_1031
  extracting CALIBRI.TTF
  extracting CALIBRIB.TTF
  extracting CALIBRII.TTF
  extracting CALIBRIZ.TTF
  extracting CAMBRIA.TTC
  extracting CAMBRIAB.TTF
  extracting CAMBRIAI.TTF
  extracting CAMBRIAZ.TTF
  extracting CANDARA.TTF
  extracting CANDARAB.TTF
  extracting CANDARAI.TTF
  extracting CANDARAZ.TTF
  extracting CONSOLA.TTF
  extracting CONSOLAB.TTF
  extracting CONSOLAI.TTF
  extracting CONSOLAZ.TTF
  extracting CONSTAN.TTF
  extracting CONSTANB.TTF
  extracting CONSTANI.TTF
  extracting CONSTANZ.TTF
  extracting CORBEL.TTF
  extracting CORBELB.TTF
  extracting CORBELI.TTF
  extracting CORBELZ.TTF
  extracting SEGOEUI.TTF
  extracting SEGOEUIB.TTF
  extracting SEGOEUII.TTF
  extracting SEGOEUIZ.TTF
  extracting MSOINTL.DLL_1031
  extracting ALRTINTL.DLL_1031
  extracting XLLEX.DLL_1031
  extracting FPSRVUTL.DLL
  extracting FPWEC.DLL
  extracting MSO.DLL
  extracting MSOHEV.DLL
  extracting MSOHTMED.EXE
  extracting MOFL.DLL_0001
  extracting FPERSON.DLL
  extracting FNAME.DLL_0001
  extracting RICHED20.DLL_0001
  extracting SEQCHK10.DLL
  extracting SAEXT.DLL_0001
  extracting MSORES.DLL
  extracting OART.DLL
  extracting OGL.DLL
  extracting OFFICE.ODF
  extracting MSPTLS.DLL_0001
  extracting XLSRVINTL.DLL_1031
  extracting msxml5.dll.AB5E1073_AD9B_48DF_B07F_3E445B5A45CF
  extracting ul_msvcr80.dll.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting ul_msvcm80.dll.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting manifest.8.0.50727.762.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting msvcr80.dll.8.0.50727.762.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting ul_msvcp80.dll.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting ul_catalog.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting ul_manifest.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting catalog.8.0.50727.762.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting msvcm80.dll.8.0.50727.762.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting msvcp80.dll.8.0.50727.762.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting nosxs_msvcr80.dll.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting nosxs_msvcp80.dll.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting nosxs_msvcm80.dll.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
  extracting ul_manifest.63E949F6_03BC_5C40_FF1F_C8B3B9A1E18E
  extracting catalog.8.0.50727.762.63E949F6_03BC_5C40_FF1F_C8B3B9A1E18E
  extracting manifest.8.0.50727.762.63E949F6_03BC_5C40_FF1F_C8B3B9A1E18E
  extracting ul_catalog.63E949F6_03BC_5C40_FF1F_C8B3B9A1E18E
  extracting msxml5r.dll.D179CD08_691D_4F49_896B_9D5BD843AC8A

All done, no errors.
```

Done!

So if we have a way of matching file size to identify the file to extract out, it will work!

**Comment by ronaldtse** [comment]
Clarification: So the 'xlview.msi' file is an OLE2 file, like `.doc`, `.xls` which is a Windows format (https://en.wikipedia.org/wiki/Object_Linking_and_Embedding). `ruby-ole` is the only gem that parses OLE in Ruby.

This gem allows us to extract files from this `xlview.msi` file.

**Comment by ronaldtse** [comment]
@abunashir this task will require a `ole_extractor` using `ruby-ole` and a method `extract_file_by_filesize(size)` to match the file size of `XLVIEW.CAB`.

**Comment by abunashir** [comment]
Would it be okay if we look into it after our next release, I'm a little bit skeptical to add different dependencies to extract a cab/msi file, maybe let's keep looking into it and if we can figure out a way to use single dependency to extract any kind of cab file or even find a different source for Segoe font?

**Comment by ronaldtse** [comment]
> skeptical to add different dependencies to extract a cab/msi file, maybe let's keep looking into it and if we can figure out a way to use single dependency to extract any kind of cab file 

Don't think there is any alternative... The msi file is not a cab, and not a zip.

I already spent lots of time searching an alternative MS-licensed file for Segoe UI but there does not seem to be another one.

**Comment by ronaldtse** [comment]
This needs to be moved to fontist/formulas#29.

**Comment by abunashir** [comment]
Thanks for the update @ronaldtse, @alexeymorozov: Can you take this over?

**Comment by alexeymorozov** [comment]
> Thanks for the update @ronaldtse, @alexeymorozov: Can you take this over?

Yeap :) Let's do it

**Comment by alexeymorozov** [comment]
:) Done in #152 and fontist/formulas#31

**Pull request closed without merging**
