### PR TITLE
#187 add GHA release workflow

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #187

@ronaldtse could you please add `secrets.FONTIST_CI_RUBYGEMS_API_KEY`

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@alexeymorozov FYI Once this PR will be merged you can simply commit version update to gemspec, `git tag v... && git push --tags` and release workflow will do everything else. Let me know if this acceptable/helpful for you

**Comment by alexeymorozov** [comment]
It would be much less error-prone 👍 Thanks!

**Review by alexeymorozov — APPROVED** [review]

**Comment by CAMOBAP** [comment]
@ronaldtse could you please confirm that `secrets.FONTIST_CI_RUBYGEMS_API_KEY` setted

**Comment by ronaldtse** [comment]
Confirm that `secrets.FONTIST_CI_RUBYGEMS_API_KEY` is added.

**Pull request merged**
