### PR TITLE
System detection

### LINKED ISSUE #175: Windows: unable to detect system fonts that already exist
Looks like fontist can't detect bold, italic, bold/italic system fonts.

OS: Windows7 64-bit.
In the folder C:\Windows\Fonts\ there are system fonts files:
- arial.ttf
- arialbd.ttf
- arialbi.ttf
- ariali.ttf

File `arial.install.yml`:
```
Arial:
  - Regular
  - Bold
  - Italic
  - Bold Italic
```

Command: `fontist manifest-install --confirm-license arial.install.yml`

Output:
```
Downloading font "arial_black" from https://gitlab.com/fontmirror/archive/-/raw/master/arialb32.exe
Downloads: 0MB/0MB (100.00%) (cache)
Installing font "arial_black".
Fonts installed at:
- C:/Users/User/.fontist/fonts/AriBlk.TTF
Downloading font "arial_black" from https://gitlab.com/fontmirror/archive/-/raw/master/arialb32.exe
Downloads: 0MB/0MB (100.00%) (cache)
Installing font "arial_black".
Fonts installed at:
- C:/Users/User/.fontist/fonts/AriBlk.TTF
Downloading font "arial_black" from https://gitlab.com/fontmirror/archive/-/raw/master/arialb32.exe
Downloads: 0MB/0MB (100.00%) (cache)
Installing font "arial_black".
Fonts installed at:
- C:/Users/User/.fontist/fonts/AriBlk.TTF
---
Arial:
  Regular:
  - C:/Windows/Fonts/arial.ttf
  - C:/Windows/Fonts/arialbd.ttf
  - C:/Windows/Fonts/arialbi.ttf
  - C:/Windows/Fonts/ariali.ttf
  - C:/Windows/Fonts/ARIALN.TTF
  - C:/Windows/Fonts/ARIALNB.TTF
  - C:/Windows/Fonts/ARIALNBI.TTF
  - C:/Windows/Fonts/ARIALNI.TTF
  Bold: []
  Italic: []
  Bold Italic: []
```

Questions:
1. Why Arial **Black** font installed?
2. arialbd.ttf - is bold, but placed in Regular array, arialbi.ttf - is italic, but placed in Regular array, etc.

### PR DESCRIPTION
**Pull request by alexeymorozov**
Closes #175

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Thank you @alexeymorozov !

**Comment by ronaldtse** [comment]
@alexeymorozov can you help release a new version for this? Thanks!

**Comment by alexeymorozov** [comment]
Released as v1.7.1 🚀

**Comment by ronaldtse** [comment]
Thanks!

**Pull request merged**
