### PR TITLE
Ruby 2.7 minimal target version requirement

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@CAMOBAP should this PR be merged? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse I think so, But because I just updated it , I would like to get @maxirmx  feedback first because he is original author

**Comment by maxirmx** [comment]
@ronaldtse @CAMOBAP It looks like it fails on Ruby 3.2 due to issues with several gems
I can look at it if necessary

**Comment by CAMOBAP** [comment]
@maxirmx thanks for feedback I propose to fix it in separate PR, Goint to merge this one

**Pull request merged**
