### PR TITLE
#249 add SOCKS support + documentation to README

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #249

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@alexeymorozov I had the same failure locally but after `git clean -fdx spec/fixtures` they are gone. Is there anything similar that should be done to make this PR green?

**Comment by ronaldtse** [comment]
@alexeymorozov could you please help update the RSpecs so as to prevent future failures? Thanks!

**Comment by ronaldtse** [comment]
Somehow one test is failing: https://github.com/fontist/fontist/pull/252/checks?check_run_id=3159105396

**Comment by alexeymorozov** [comment]
Yeap, am already working on it. These tests would use new way of isolation between specs, so it by design would decrease chance of this happening.

**Comment by ronaldtse** [comment]
@alexeymorozov I see that this is passing -- can we merge it now? Thanks!

**Comment by alexeymorozov** [comment]
Yes, I will create another PR for reworked specs.

**Pull request merged**
