### PR TITLE
#326 don't requirest --size-limit if resource already downloaded

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #326

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP can we also add a spec to test this behavior? Thanks.

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@CAMOBAP the remaining failure is due to testing Metanorma on Windows. Can you fix that in a separate PR? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse yep, interesting that we have the same issue on `formulas` repo. Here we have two parts:
 - `fontinst`'s test (I will fix as part of this PR)
 - metanorma will be fixed on `metanorma-cli` repo https://github.com/metanorma/metanorma-cli/issues/303

**Comment by ronaldtse** [comment]
@CAMOBAP is this going to be merged soon? Otherwise maybe @alexeymorozov can handle this?

**Comment by alexeymorozov** [comment]
Yes, I will investigate the failing spec

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thank you @alexeymorozov !

**Pull request merged**
