### PR TITLE
Manifest full_name

### PR DESCRIPTION
**Pull request by alexeymorozov**
See https://github.com/metanorma/mn2pdf/issues/52

### CODE REVIEW

**Comment by alexeymorozov** [comment]
Would appreciate a review @ronaldtse

**Review by ronaldtse — APPROVED** [review]
LGTM, thanks @alexeymorozov !

**Comment by ronaldtse** [comment]
@alexeymorozov could you help bump version and release gem, and ping @Intelligent2013 when done? Thanks!

**Comment by alexeymorozov** [comment]
Yes, it's released as v1.7.0

/cc @Intelligent2013

**Comment by Intelligent2013** [comment]
@alexeymorozov thanks.

**Pull request merged**
