### PR TITLE
Install only sufficient formula

### PR DESCRIPTION
**Pull request by alexeymorozov**
Closes https://github.com/fontist/formulas/issues/109

### CODE REVIEW

**Comment by ronaldtse** [comment]
@alexeymorozov I believe we have to support these use cases:

1. User wants a specific version of font. Then we install that.
2. User wants to install smallest size of a font. Then we find out the version with smallest size and install that.
3. User wants to install the newest font. We have to find the newest version and install that.
4. User has a specific criteria - below a certain size (e.g. don't want to download full MS Office) but the newest version according to that).

**Comment by alexeymorozov** [comment]
@ronaldtse Got it. Can implement with CLI (or Ruby) options. The 3 one would be a default case? With filtering by size if they have the same versions?

**Comment by ronaldtse** [comment]
Probably 4 should be the default? 

For example, some of the newest MS fonts require download of the latest office which can be gigabytes large. Maybe we just need to select the newest version under 100 or 300 MB unless the user specifies that size is not an issue or accepting 3GB or more downloads...

**Comment by alexeymorozov** [comment]
Sounds even better! So first let's choose between small-size formulas by version. The size can be chosen when we add this attribute to formulas, and see which is a common size.

**Comment by alexeymorozov** [comment]
Among 1458 formulas there are only 8 that are above 100 MB, with median of 0.095 MB.

```
chinese_simplified.yml, 317
japanese.yml, 240
chinese_traditional.yml, 236
korean.yml, 228
guttman.yml, 223
arabic.yml, 209
adobe_reader_20.yml, 169
work_sans.yml, 110

source.yml, 97
stix.yml, 78
segoe_ui.yml, 74
google/noto_serif_sc.yml, 63
adobe_reader_19.yml, 60
cleartype.yml, 60
yu.yml, 53
google/noto_sans_sc.yml, 42
google/noto_serif_kr.yml, 36
google/noto_serif_jp.yml, 35
google/noto_serif_tc.yml, 33
google/shippori_mincho_b1.yml, 33

```

**Comment by ronaldtse** [comment]
@alexeymorozov these formulas are reasonably sized indeed.

I was worrying about these ones:

**Comment by alexeymorozov** [comment]
Then will use 300 MB as a size limit. It would help to avoid changing current behavior when installing formulas with size from 100 to 300 MB.

Currently this PR supports several ways to install large formulas:

1. Use the `--newest` option (case 3)
2. Use the `--version` option (case 1)
3. Use the `--smallest` option (case 2, may be counter-intuitive but it selects the smallest ignoring the limit)
4. Specify larger `--size-limit` option

Thought of a `--ignore-size-limit` option but it seems it would work as the `--newest` option:
1. ignores the limit
2. searches for the newest version
3. and if there are several ones, chooses the smallest

**Comment by ronaldtse** [comment]
Thank you @alexeymorozov !

**Pull request merged**
