### PR TITLE
No progress

### LINKED ISSUE #213: [FEATURE] Add --no-progress flag
### Problem

Our CI logs suffer from a lot of logs like this:

```
...
Downloads: 96MB/96MB (100.00%)
...
```

It's hard to open/browse them

### Proposed solution

Previously we have absolutely the same issue with `chocolatey install`, till we find that there is `--no-progress` option. I propose to implement the same mechanism in `fontist`.

Once this option passed `fontist ...` should not print download progress. Because it already prints the message `Downloading font "FONT_NAME" from URL`

@ronaldtse @alexeymorozov how do you think about this request?

### PR DESCRIPTION
**Pull request by alexeymorozov**
Closes #213

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @alexeymorozov !

**Comment by ronaldtse** [comment]
@CAMOBAP can we use this new `--no-progress` option for Metanorma fontist installs? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse Definitely. I propose to add the sample property for `metanorma-cli`. To be able to control ithttps://github.com/metanorma/metanorma-cli/issues/227

**Comment by ronaldtse** [comment]
Sure, agree.

**Pull request merged**
