### PR TITLE
#308 checkout main branch in favor of master if exists

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #308

### CODE REVIEW

**Comment by CAMOBAP** [comment]
With this fix: `bundle exec ruby exe/fontist install "BSI Gesta"` works as expected

```
Font "BSI Gesta" not found locally.
Downloading font "private/metanorma/bsi_gesta" from https://api.github.com/repos/metanorma/bsi-brand-assets/releases/assets/94964556
Downloading: 100% (0/0 MiB), 0.12 MiB/s, done.
Installing font "private/metanorma/bsi_gesta".
Fonts installed at:
- /Users/camobap/.fontist/fonts/BSIGesta-Bold.otf
- /Users/camobap/.fontist/fonts/BSIGesta-BoldItalic.otf
- /Users/camobap/.fontist/fonts/BSIGesta-Italic.otf
- /Users/camobap/.fontist/fonts/BSIGesta-Light.otf
- /Users/camobap/.fontist/fonts/BSIGesta-LightItalic.otf
- /Users/camobap/.fontist/fonts/BSIGesta-Medium.otf
- /Users/camobap/.fontist/fonts/BSIGesta-MediumItalic.otf
- /Users/camobap/.fontist/fonts/BSIGesta.otf
```

Maybe we should add more "smart" check and compare commit dates for master and main too.

@ronaldtse @alexeymorozov I'm out to feedback/suggestions

**Comment by ronaldtse** [comment]
@CAMOBAP I'm fine with the fix but the macOS builds are failing now. Are they due to extract_ttc?

https://github.com/fontist/fontist/actions/runs/4153280765/jobs/7184810199
```
  15) Fontist::Import::Macos generates formula with necessary attributes
      Failure/Error: require "extract_ttc"

      LoadError:
        Could not open library '/Users/runner/work/fontist/fontist/vendor/bundle/ruby/2.6.0/gems/extract_ttc-0.3.1-x86_64-darwin/lib/stripttc.so': dlopen(/Users/runner/work/fontist/fontist/vendor/bundle/ruby/2.6.0/gems/extract_ttc-0.3.1-x86_64-darwin/lib/stripttc.so, 0x0005): tried: '/Users/runner/work/fontist/fontist/vendor/bundle/ruby/2.6.0/gems/extract_ttc-0.3.1-x86_64-darwin/lib/stripttc.so' (no such file)
      # ./vendor/bundle/ruby/2.6.0/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib'
      # ./vendor/bundle/ruby/2.6.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `map'
      # ./vendor/bundle/ruby/2.6.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `ffi_lib'
      # ./vendor/bundle/ruby/2.6.0/gems/extract_ttc-0.3.1-x86_64-darwin/lib/extract_ttc.rb:25:in `<module:ExtractTtc>'
      # ./vendor/bundle/ruby/2.6.0/gems/extract_ttc-0.3.1-x86_64-darwin/lib/extract_ttc.rb:5:in `<top (required)>'
      # ./lib/fontist/import/files/collection_file.rb:1:in `require'
      # ./lib/fontist/import/files/collection_file.rb:1:in `<top (required)>'
      # ./lib/fontist/import/recursive_extraction.rb:2:in `require_relative'
      # ./lib/fontist/import/recursive_extraction.rb:2:in `<top (required)>'
      # ./lib/fontist/import/create_formula.rb:2:in `require_relative'
      # ./lib/fontist/import/create_formula.rb:2:in `<top (required)>'
      # ./lib/fontist/import/macos.rb:3:in `require'
      # ./lib/fontist/import/macos.rb:3:in `<top (required)>'
      # ./spec/fontist/import/macos_spec.rb:5:in `require'
      # ./spec/fontist/import/macos_spec.rb:5:in `block (2 levels) in <top (required)>'
```

It looks like the latest extract_ttc has issues running on macOS right now.

**Comment by CAMOBAP** [comment]
Yep, interested that they works locally

I am investigating this problem

**Comment by CAMOBAP** [comment]
@ronaldtse macos related issue will be resolved after https://github.com/fontist/extract_ttc/pull/16 merge and release

**Pull request merged**
