### PR TITLE
Auto-add license

### PR DESCRIPTION
**Pull request by alexeymorozov**

### CODE REVIEW

**Comment by ronaldtse** [comment]
macOS build failing due to execution timeout?

**Comment by alexeymorozov** [comment]
Could be but this time seems it was a real failing. I've changed a method in code and forgot to change it in specs (`say` -> `error`).

**Comment by alexeymorozov** [comment]
This is ready for review @ronaldtse

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thanks @alexeymorozov !

**Pull request merged**
