### PR TITLE
Performance

### PR DESCRIPTION
**Pull request by alexeymorozov**
See #254

### CODE REVIEW

**Comment by alexeymorozov** [comment]
@ronaldtse If anything, please tell, I can make an extra effort.

**Comment by ronaldtse** [comment]
@alexeymorozov would you be able to improve the performance further? What's the idea for improvement?

**Comment by ronaldtse** [comment]
Let's merge this first. Thanks!

**Comment by alexeymorozov** [comment]
> @alexeymorozov would you be able to improve the performance further? What's the idea for improvement?

I thought to refactor code a little more, if there are some concerns. As for performance, it should speed up from 13 sec to 700 ms. If we would need it faster, I can profile more and try to eliminate other bottlenecks.

**Pull request merged**
