### PR TITLE
Move Google update to formulas

### PR DESCRIPTION
**Pull request by alexeymorozov**
See #253 

Formulas PR: https://github.com/fontist/formulas/pull/102

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @alexeymorozov , let me know when this is mergeable. The Google Fonts check is still failing daily.

**Comment by alexeymorozov** [comment]
@ronaldtse Made it green. The next steps could be:

1. Create a branch in formulas, and update formulas there, then PR can be manually checked and merged
2. Or even autoupdate Google formulas on the v2 branch every day

**Comment by ronaldtse** [comment]
Nice! @alexeymorozov what is the most carefree solution we can have?

**Comment by alexeymorozov** [comment]
I think, autoupdate would be more carefree, and anyway we would have an ability to revert the changes.

Will try to implement.

**Comment by ronaldtse** [comment]
Agree, thanks @alexeymorozov .

**Comment by alexeymorozov** [comment]
@ronaldtse This can be merged now. It will automatically update google formulas every day.

**Comment by ronaldtse** [comment]
Thanks @alexeymorozov !

**Pull request merged**
