### PR TITLE
YAML formulas

### PR DESCRIPTION
**Pull request by alexeymorozov**
See #114

### CODE REVIEW

**Comment by alexeymorozov** [comment]
@ronaldtse, kindly asking for review :)

Converted YAML formulas are here: #133

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Looks good, thanks @alexeymorozov ! Feel free to merge when ready (and the formulas pass)

**Comment by alexeymorozov** [comment]
Thanks, @ronaldtse ! A final commit passes, so both are merged to master now

**Comment by alexeymorozov** [comment]
If we ever need the convertation script, it's in the `convert-formulas` branch, here https://github.com/fontist/fontist/commit/2bf7b5d0de62a2f8af0dd7ad966033ac1b2bb173

**Comment by ronaldtse** [comment]
@alexeymorozov for the conversion script can you just place it in master under bin/? It might be useful in the future.

**Comment by alexeymorozov** [comment]
@ronaldtse Ok :) It's done, placed under bin/

**Comment by ronaldtse** [comment]
Thanks @alexeymorozov !

**Pull request merged**
